/**
 * Transparency panel explaining how analysis was performed.
 */
export default function AnalysisSummary({ analysisMeta }) {
  if (!analysisMeta) return null;

  const { mode, programsScreened, analyzedAt, providerLabel, fallbackReason } = analysisMeta;
  const isAI = mode === 'gemini' || mode === 'openai';

  return (
    <div className="mx-auto mb-8 max-w-4xl rounded-lg border border-primary-200 bg-primary-50 p-4 sm:p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-sm font-semibold uppercase tracking-wide text-primary-800">
            How This Analysis Works
          </h2>
          <p className="mt-1 text-sm text-primary-900">
            {isAI
              ? `Recommendations were generated by ${providerLabel} using your profile and structured eligibility rules.`
              : `${providerLabel} compared your profile against ${programsScreened} program rule sets using transparent, criterion-by-criterion evaluation.`}
          </p>
        </div>
        <span className="inline-flex rounded-full border border-primary-300 bg-white px-3 py-1 text-xs font-semibold text-primary-700">
          {isAI ? 'AI-Powered' : 'Rule-Based Demo'}
        </span>
      </div>

      <ul className="mt-3 grid gap-1 text-xs text-primary-800 sm:grid-cols-3">
        <li>Programs screened: {programsScreened}</li>
        <li>Analysis mode: {providerLabel}</li>
        <li>
          Analyzed: {new Date(analyzedAt).toLocaleString()}
        </li>
      </ul>

      {fallbackReason && (
        <p className="mt-3 text-xs text-amber-800">
          AI service unavailable — results use rule-based fallback. ({fallbackReason})
        </p>
      )}

      <p className="mt-3 text-xs text-primary-700">
        Your data is processed in this session only and is not stored on any server.
        ClearPath never claims definite qualification — always verify through official sources.
      </p>
    </div>
  );
}
